FROM openjdk:8-jdk-alpine
COPY ./target/SpringBootMSC-0.0.1-SNAPSHOT.jar /usr/src/server/
WORKDIR /usr/src/Java-spring-cloud-master
EXPOSE 8888
CMD ["java","-jar","/usr/src/Java-spring-cloud-master/target/SpringBootMSC-0.0.1-SNAPSHOT.jar"]